[build][build]

  base = "."  base = "."

  publish = "."  publish = "auctus-app"

  functions = "netlify/functions"  functions = "netlify/functions"



[functions][functions]

  node_bundler = "esbuild"  node_bundler = "esbuild"

